### ISSUE TITLE
heatmap example broken on `featured.plutojl.org`

### ISSUE THREAD

**Issue by declann** [JuliaPluto/featured#10]
Hey guys, awesome work with Pluto!

Heatmap example appears broken for me on the website:

https://featured.plutojl.org/plot/heatmap.html

![image](https://github.com/JuliaPluto/featured/assets/353214/1eeb8935-ead2-42a8-a683-533c90860ba2)

Something went wrong in the build process?

Thankfully it's working locally & looking nice :)

![image](https://github.com/JuliaPluto/featured/assets/353214/c78c6581-0cc3-4aa3-9769-e24d3bebccf2)

**Comment by pankgeorg** [comment]
Thanks for the report! I've retriggered the workflow, let's see what will come out of it :)

**Comment by pankgeorg** [comment]
so, the issue seems to be with GLMakie 


```
Failed to precompile GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a] to /home/runner/.julia/compiled/v1.6/GLMakie/jl_WQ5viK.
┌ Warning:     OpenGL/GLFW wasn't loaded correctly or couldn't be initialized.
│     This likely means, you're on a headless server without having OpenGL support setup correctly.
│     Have a look at the troubleshooting section in the readme:
│     https://github.com/MakieOrg/Makie.jl/tree/master/GLMakie#troubleshooting-opengl.
└ @ GLMakie ~/.julia/packages/GLMakie/OVxAi/src/gl_backend.jl:4
ERROR: LoadError: LoadError: InitError: Exception[GLFW.GLFWError(GLFW.PLATFORM_ERROR, "X11: The DISPLAY environment variable is missing"), ErrorException("glfwInit failed")]
```

Can we use CairoMakie instead @ariguiba ?

**Comment by behinger** [comment]
the way it is coded right now, we cannot use CairoMakie - as it will redraw the plot everytime + probably wont work with the 3D anyway.

The solution might rather be, to modify the github action, adding:
```yaml
with:
          prefix:  DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24'
```
to gain a fake X session

**Comment by declann** [comment]
Looks like one of the fixes worked! 🙌

**Comment by fonsp** [comment]
Woohooo thanks benedikt!!

Maybe we should add this config as an option to static-export-template? Or by default? How much time does it add?

**Comment by behinger** [comment]
I'm happy too that it worked :-)

According to the last run, it added 30s to install the packages. Whether starting something with xvfb-run takes additional time, I dont know (I would rather guess, not that much). The time is maybe actually less of an issue, rather than the older & non-updating ubuntu-20 (compared to ubuntu-latest). 

Could be an additional yaml file? exportPlutoGL or something?

PS: export-static looks really useful!!
