### ISSUE TITLE
Adapting for Personal Templates

### ISSUE THREAD

**Issue by stefanbringuier** [JuliaPluto/featured#11]
I just forked this repo and have been trying to use it as a way to have the frontend load my custom Pluto notebook templates.

All the GitHub actions pass and I followed the details in the [pluto-developer-instructions](https://github.com/JuliaPluto/pluto-developer-instructions/blob/98e86bd96b4961f04a2a37d2294b07945be104b2/How%20to%20update%20the%20featured%20notebooks.md).

The problem is I don't see any nb cards/entries (only 1 right now):

<https://stefanbringuier.github.io/PlutoNotebookTemplates/>

And same on my local Pluto server instance:

![image](https://github.com/JuliaPluto/featured/assets/2709082/27520d4e-fc3e-4210-aede-416eceda2603)

Everything looks correct to me on the `dist` branch: https://github.com/stefanbringuier/PlutoNotebookTemplates/tree/dist

This would be very helpful for me as I have a lot of template nb files that would be nice to quickly select from the landing page.

**Comment by Pangoraw** [comment]
You need to add a tag in the notebooks' frontmatter:

https://github.com/JuliaPluto/featured/blob/a004fdb6fc31c8e9fadc511e127c957fe9647415/src/basic_templates/BasicPlutoTemplate.jl#L12

which corresponds to one of the tags of the categories defined in the json config file (example: `basic_templates` or `specific_templates`)

https://github.com/JuliaPluto/featured/blob/a004fdb6fc31c8e9fadc511e127c957fe9647415/src/pluto_export_configuration.json#L10

**Comment by stefanbringuier** [comment]
Worked! Thanks for catching this for me.

**Comment by stefanbringuier** [comment]
Seems I have forgotten or can't get my personal templates showing up on Pluto's landing page leveraging featured notebooks repo. I have a local copy of pluto where I modify the `frontend/featured_sources.js` and follow the [developer instructions for updating the featured notebooks](https://github.com/JuliaPluto/pluto-developer-instructions/blob/98e86bd96b4961f04a2a37d2294b07945be104b2/How%20to%20update%20the%20featured%20notebooks.md) to have them displayed but I can't get it to work again. 

Any guidance or laid out steps for this would be much appreciated.

Also would templates like [these](https://stefanbringuier.github.io/PlutoNotebookTemplates/) be suitable for contribution? In general would be nice if I could easily incorporate my templates without having to modify and run a cloned branch of Pluto.

**Comment by fonsp** [comment]
Hi! I just added your export json to `featured_sources.json` and it seems to work. See the green lines on the left to see which lines are different from the `main` branch of Pluto

<img width="531" alt="image" src="https://github.com/user-attachments/assets/19fa8521-9d60-4c03-8194-922fab50271a">

**Comment by fonsp** [comment]
You can also start Pluto normally and go to:

http://localhost:1234/?featured_source_url=https%3A%2F%2Fstefanbringuier.github.io%2FPlutoNotebookTemplates%2Fpluto_export.json 

(I used https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent to encode the url)

**Comment by fonsp** [comment]
About contributing: maybe a sample notebook about PlutoExtras might be better? But I think some PlutoExtras featured need polishing before

**Comment by stefanbringuier** [comment]
> You can also start Pluto normally and go to:
> 
> ```
> http://localhost:1234/?featured_source_url=https%3A%2F%2Fstefanbringuier.github.io%2FPlutoNotebookTemplates%2Fpluto_export.json 
> ```
> 
> (I used https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent to encode the url)

This is perfect! Thanks Fons.

Closing again.
